# Setup
title:        Kelechi Ibekwe
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kele
  url:        http://KeleAutvmn.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown